### PR TITLE
Add boptest and energyplus libs.

### PR DESCRIPTION
**Pull request by craig8**

### CODE REVIEW

**Comment by netomi** [comment]
Just to double check, there are already 2 repos

- volttron-boptest
- volttron-energyplus

shall they be renamed to volttron-lib-boptest and volttron-lib-energyplus respectively or coexist?

**Comment by craig8** [comment]
Up until yesterday at our meeting I would have said yeah we want both, but now we are going to consolidate and have those two tightly coupled projects in one repo.

**Comment by netomi** [comment]
np, ty for starting to raise PRs anyway.

**Comment by fperezel** [comment]
Hello,

If you require additional information about GitHub Secret scanning before reviewing this pull request, please refer to the following GitHub document: [Link to GitHub Document About secret scanning]( https://docs.github.com/en/code-security/secret-scanning/about-secret-scanning).

Feel free to reach out if you have any questions.

Thank you,
FP

**Pull request closed without merging**
